### ISSUE TITLE
Optional catch all routes [[...category]] route ?

### ISSUE THREAD

**Issue by revskill10** [ckastbjerg/next-type-safe-routes#12]
Hi, thanks for great library.

I have one issue about wildcard route, like `/store/[store]/[[...category]]` , i see it generates as route `/store/[store]/[[` only.

Could you please check this use case ?

**Comment by ckastbjerg** [comment]
Hi Truong!

Glad you like it :) And thanks for submitting this issue.

I didn't think about that use case, no. I will have a look at supporting it very soon.

/Christian

**Comment by ckastbjerg** [comment]
@revskill10 after a bit of thinking, I feel like I found a decent solution for this use case :) 
If you have time, could you please let me know if this interface makes sense to you: https://github.com/ckastbjerg/next-type-safe-routes/pull/13?

**Comment by ckastbjerg** [comment]
I've released the changes as I didn't want to keep the PR open too long. If this doesn't solve your issue, let me know. And I'll have another look at it :)

**Comment by revskill10** [comment]
@ckastbjerg Huge thanks. I'll try out and post issues if i've got any !

**Comment by revskill10** [comment]
For further investigation, if you have a look at i18n routing, it would be awesome 👯‍♂️
