### ISSUE TITLE
Types not saved in the correct place on windows

### ISSUE THREAD

**Issue by osdiab** [ckastbjerg/next-type-safe-routes#27]
~I still need to figure out why this is happening, but~ my teammate on a project is experiencing a strange issue where the `@types` folder is being placed in the src/pages directory instead of the src directory for him. Will take a look at the code and chat with him more to see if I can find out what might be going on. Related to #18

EDIT: turns out i was right, slashes are reversed in windows:

```
{
  pagesDir: 'C:\\Users\\gus\\Documents\\dev\\spinach\\web-app\\src\\pages'
}
```

the code needs to be tolerant of that, and also probably should not just be a regex replace (if `/pages` is anywhere else in the path it'll break)

**Comment by osdiab** [comment]
I suspect it might be that he's on windows and the slashes are reversed? But double checking by asking him to print out what the pagesDir value is

**Comment by airtonix** [comment]
this is only true if you use `cmd.exe` .

most people will now be using powershell by default or wsl2
